Processing Data in Models
DJ-MrJay/My-Blog-App pull request #3
Opened 2023-05-09 21:28 UTC by DJ-MrJay

In this branch, I:
- Created model classes for all entities as shown in the [ERD diagram](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd_v1_1.png).
- Set up associations between models.
- Use models to insert data.
- Create custom methods.

2023-05-09 23:59 UTC, zainsadaqat requested changes
# Required Changes 🔁
## Hello  @DJ-MrJay 👋 🙂

You're doing a great job on your project. We're proud of you. Good job so far! 

It's OK to have bugs in your code. Please, see this code review as a chance for you to learn practical coding skills and learn new tips that can improve your code quality and help you get a better job. 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
  ✅  Correct use of GitHub Flow
  ✅  Descriptive Pull Request
  ✅  No linter errors

## Required Changes ♻️

- [ ] 

<img src="https://media0.giphy.com/media/HxnMNAEQgHqEHcGKBb/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-09 23:59 UTC, zainsadaqat commented on app/models/user.rb
> +  validates :name, presence: true
The user model must have a method that returns the 3 most recent posts as part of the project requirement. Kindly implement that method. 👍

2023-05-09 23:59 UTC, zainsadaqat commented on app/models/post.rb
> +  validates :text, presence: true
The post model must have a method that updates the posts counter for a user as it's part of the project requirement. Kindly implement that 👍

2023-05-09 23:59 UTC, zainsadaqat commented on app/models/post.rb
> +  validates :text, presence: true
The Post model must have a method that returns the 5 most recent comments for a given post as it's part of project requirement. Kindly implement that 👍

2023-05-09 23:59 UTC, zainsadaqat commented on app/models/comment.rb
> +  validates :text, presence: true
The comment model must have a method that updates the comments counter for a post as it's part of the requirement. Kindly implement that 👍

2023-05-09 23:59 UTC, zainsadaqat commented on app/models/like.rb
> +  belongs_to :post
Like model must have a method that updates the likes counter for a post as it's a project requirement. Kindly implement that 👍

2023-05-10 11:46 UTC, Qoosim approved these changes
#  *Status: Approved* :tada: :heavy_check_mark: 

Hi @DJ-MrJay, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct Gitflow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-10 11:46 UTC, Qoosim commented on app/models/comment.rb
> +  end
- [OPTIONAL] Nice job implementing required changes from the previous reviewer. I see below snippet more clean. You can check it out.
```
      def update_comments_counter
          post.increment!(:comments_counter)
      end

```

You can apply the same to other models where necessary if you like it :smile:

2023-05-12 10:56 UTC, merged

2023-07-13 07:37 UTC, prolajumokeoni reviewed
Hi @DJ-MrJay 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
-  The associations between models are set up correctly 👏🏿


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._