Controllers
DJ-MrJay/My-Blog-App pull request #5
Opened 2023-05-18 19:52 UTC by DJ-MrJay

In this milestone, I implemented the following:
For each URL in the wireframes I created:
- A route.
- An action in the correct controller.
- A view file.

View files include only placeholders written in plain HTML.

2023-05-18 20:06 UTC, Kamba56 requested changes
Hi @DJ-MrJay, 

Good job so far!!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- [x] Great job adding the controllers for users and posts👏👏👏
- [x] Good job adding the actions to controllers and corresponding HTML files

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-18 20:06 UTC, Kamba56 commented on app/controllers/users_controller.rb
> +  def show
- [ ] Great job adding the show action for users. As demanded by project requirements, kindly add the index action for users. Note; for this milestone, you can leave your actions blank.

2023-05-18 20:06 UTC, Kamba56 commented on app/views/users/show.html.erb
- [ ] Great job adding the show HTML file for the users show action. Kindly add an index.html.erb to correspond with the index action.

2023-05-18 21:54 UTC, jerryowusu approved these changes
Hi @DJ-MrJay 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![good-fine](https://github.com/DJ-MrJay/My-Blog-App/assets/65233860/cc1187e9-84ac-4150-b127-925e3103df01)


## Highlights
:heavy_check_mark: Added index action for users controller
:heavy_check_mark: Nice commit messages

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-18 23:07 UTC, merged

2023-07-17 10:24 UTC, muneebulrehman reviewed
Hi @DJ-MrJay , 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🥳
Congratulations! 🎉 

# Status: Approved✔️

## Highlights
- No linter errors
- Descriptive PR
- All technical requirements met for this milestone. 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._